export interface Surah {
  number: number;
  name: string;
  transliteration: string;
  translation: string;
  ayahs: number;
}

export const SURAHS: Surah[] = [
  {
    number: 1,
    name: "الفاتحة",
    transliteration: "Al-Fatihah",
    translation: "The Opening",
    ayahs: 7,
  },
  {
    number: 2,
    name: "البقرة",
    transliteration: "Al-Baqarah",
    translation: "The Cow",
    ayahs: 286,
  },
  {
    number: 3,
    name: "آل عمران",
    transliteration: "Ali 'Imran",
    translation: "Family of Imran",
    ayahs: 200,
  },
  {
    number: 4,
    name: "النساء",
    transliteration: "An-Nisa",
    translation: "The Women",
    ayahs: 176,
  },
  {
    number: 5,
    name: "المائدة",
    transliteration: "Al-Ma'idah",
    translation: "The Table Spread",
    ayahs: 120,
  },
  {
    number: 6,
    name: "الأنعام",
    transliteration: "Al-An'am",
    translation: "The Cattle",
    ayahs: 165,
  },
  {
    number: 7,
    name: "الأعراف",
    transliteration: "Al-A'raf",
    translation: "The Heights",
    ayahs: 206,
  },
  {
    number: 8,
    name: "الأنفال",
    transliteration: "Al-Anfal",
    translation: "The Spoils of War",
    ayahs: 75,
  },
  {
    number: 9,
    name: "التوبة",
    transliteration: "At-Tawbah",
    translation: "The Repentance",
    ayahs: 129,
  },
  {
    number: 10,
    name: "يونس",
    transliteration: "Yunus",
    translation: "Jonah",
    ayahs: 109,
  },
  {
    number: 11,
    name: "هود",
    transliteration: "Hud",
    translation: "Hud",
    ayahs: 123,
  },
  {
    number: 12,
    name: "يوسف",
    transliteration: "Yusuf",
    translation: "Joseph",
    ayahs: 111,
  },
  {
    number: 13,
    name: "الرعد",
    transliteration: "Ar-Ra'd",
    translation: "The Thunder",
    ayahs: 43,
  },
  {
    number: 14,
    name: "ابراهيم",
    transliteration: "Ibrahim",
    translation: "Abraham",
    ayahs: 52,
  },
  {
    number: 15,
    name: "الحجر",
    transliteration: "Al-Hijr",
    translation: "The Rocky Tract",
    ayahs: 99,
  },
  {
    number: 16,
    name: "النحل",
    transliteration: "An-Nahl",
    translation: "The Bee",
    ayahs: 128,
  },
  {
    number: 17,
    name: "الإسراء",
    transliteration: "Al-Isra",
    translation: "The Night Journey",
    ayahs: 111,
  },
  {
    number: 18,
    name: "الكهف",
    transliteration: "Al-Kahf",
    translation: "The Cave",
    ayahs: 110,
  },
  {
    number: 19,
    name: "مريم",
    transliteration: "Maryam",
    translation: "Mary",
    ayahs: 98,
  },
  {
    number: 20,
    name: "طه",
    transliteration: "Ta-Ha",
    translation: "Ta-Ha",
    ayahs: 135,
  },
  {
    number: 21,
    name: "الأنبياء",
    transliteration: "Al-Anbya",
    translation: "The Prophets",
    ayahs: 112,
  },
  {
    number: 22,
    name: "الحج",
    transliteration: "Al-Hajj",
    translation: "The Pilgrimage",
    ayahs: 78,
  },
  {
    number: 23,
    name: "المؤمنون",
    transliteration: "Al-Mu'minun",
    translation: "The Believers",
    ayahs: 118,
  },
  {
    number: 24,
    name: "النور",
    transliteration: "An-Nur",
    translation: "The Light",
    ayahs: 64,
  },
  {
    number: 25,
    name: "الفرقان",
    transliteration: "Al-Furqan",
    translation: "The Criterion",
    ayahs: 77,
  },
  {
    number: 26,
    name: "الشعراء",
    transliteration: "Ash-Shu'ara",
    translation: "The Poets",
    ayahs: 227,
  },
  {
    number: 27,
    name: "النمل",
    transliteration: "An-Naml",
    translation: "The Ant",
    ayahs: 93,
  },
  {
    number: 28,
    name: "القصص",
    transliteration: "Al-Qasas",
    translation: "The Stories",
    ayahs: 88,
  },
  {
    number: 29,
    name: "العنكبوت",
    transliteration: "Al-'Ankabut",
    translation: "The Spider",
    ayahs: 69,
  },
  {
    number: 30,
    name: "الروم",
    transliteration: "Ar-Rum",
    translation: "The Romans",
    ayahs: 60,
  },
  {
    number: 31,
    name: "لقمان",
    transliteration: "Luqman",
    translation: "Luqman",
    ayahs: 34,
  },
  {
    number: 32,
    name: "السجدة",
    transliteration: "As-Sajdah",
    translation: "The Prostration",
    ayahs: 30,
  },
  {
    number: 33,
    name: "الأحزاب",
    transliteration: "Al-Ahzab",
    translation: "The Combined Forces",
    ayahs: 73,
  },
  {
    number: 34,
    name: "سبأ",
    transliteration: "Saba",
    translation: "Sheba",
    ayahs: 54,
  },
  {
    number: 35,
    name: "فاطر",
    transliteration: "Fatir",
    translation: "Originator",
    ayahs: 45,
  },
  {
    number: 36,
    name: "يس",
    transliteration: "Ya-Sin",
    translation: "Ya Sin",
    ayahs: 83,
  },
  {
    number: 37,
    name: "الصافات",
    transliteration: "As-Saffat",
    translation: "Those who set the Ranks",
    ayahs: 182,
  },
  {
    number: 38,
    name: "ص",
    transliteration: "Sad",
    translation: "The Letter Saad",
    ayahs: 88,
  },
  {
    number: 39,
    name: "الزمر",
    transliteration: "Az-Zumar",
    translation: "The Troops",
    ayahs: 75,
  },
  {
    number: 40,
    name: "غافر",
    transliteration: "Ghafir",
    translation: "The Forgiver",
    ayahs: 85,
  },
  {
    number: 41,
    name: "فصلت",
    transliteration: "Fussilat",
    translation: "Explained in Detail",
    ayahs: 54,
  },
  {
    number: 42,
    name: "الشورى",
    transliteration: "Ash-Shuraa",
    translation: "The Consultation",
    ayahs: 53,
  },
  {
    number: 43,
    name: "الزخرف",
    transliteration: "Az-Zukhruf",
    translation: "The Ornaments of Gold",
    ayahs: 89,
  },
  {
    number: 44,
    name: "الدخان",
    transliteration: "Ad-Dukhan",
    translation: "The Smoke",
    ayahs: 59,
  },
  {
    number: 45,
    name: "الجاثية",
    transliteration: "Al-Jathiyah",
    translation: "The Crouching",
    ayahs: 37,
  },
  {
    number: 46,
    name: "الأحقاف",
    transliteration: "Al-Ahqaf",
    translation: "The Wind-Curved Sandhills",
    ayahs: 35,
  },
  {
    number: 47,
    name: "محمد",
    transliteration: "Muhammad",
    translation: "Muhammad",
    ayahs: 38,
  },
  {
    number: 48,
    name: "الفتح",
    transliteration: "Al-Fath",
    translation: "The Victory",
    ayahs: 29,
  },
  {
    number: 49,
    name: "الحجرات",
    transliteration: "Al-Hujurat",
    translation: "The Rooms",
    ayahs: 18,
  },
  {
    number: 50,
    name: "ق",
    transliteration: "Qaf",
    translation: "The Letter Qaf",
    ayahs: 45,
  },
  {
    number: 51,
    name: "الذاريات",
    transliteration: "Adh-Dhariyat",
    translation: "The Winnowing Winds",
    ayahs: 60,
  },
  {
    number: 52,
    name: "الطور",
    transliteration: "At-Tur",
    translation: "The Mount",
    ayahs: 49,
  },
  {
    number: 53,
    name: "النجم",
    transliteration: "An-Najm",
    translation: "The Star",
    ayahs: 62,
  },
  {
    number: 54,
    name: "القمر",
    transliteration: "Al-Qamar",
    translation: "The Moon",
    ayahs: 55,
  },
  {
    number: 55,
    name: "الرحمن",
    transliteration: "Ar-Rahman",
    translation: "The Beneficent",
    ayahs: 78,
  },
  {
    number: 56,
    name: "الواقعة",
    transliteration: "Al-Waqi'ah",
    translation: "The Inevitable",
    ayahs: 96,
  },
  {
    number: 57,
    name: "الحديد",
    transliteration: "Al-Hadid",
    translation: "The Iron",
    ayahs: 29,
  },
  {
    number: 58,
    name: "المجادلة",
    transliteration: "Al-Mujadila",
    translation: "The Pleading Woman",
    ayahs: 22,
  },
  {
    number: 59,
    name: "الحشر",
    transliteration: "Al-Hashr",
    translation: "The Exile",
    ayahs: 24,
  },
  {
    number: 60,
    name: "الممتحنة",
    transliteration: "Al-Mumtahanah",
    translation: "She that is to be examined",
    ayahs: 13,
  },
  {
    number: 61,
    name: "الصف",
    transliteration: "As-Saf",
    translation: "The Ranks",
    ayahs: 14,
  },
  {
    number: 62,
    name: "الجمعة",
    transliteration: "Al-Jumu'ah",
    translation: "Friday",
    ayahs: 11,
  },
  {
    number: 63,
    name: "المنافقون",
    transliteration: "Al-Munafiqun",
    translation: "The Hypocrites",
    ayahs: 11,
  },
  {
    number: 64,
    name: "التغابن",
    transliteration: "At-Taghabun",
    translation: "The Mutual Disillusion",
    ayahs: 18,
  },
  {
    number: 65,
    name: "الطلاق",
    transliteration: "At-Talaq",
    translation: "The Divorce",
    ayahs: 12,
  },
  {
    number: 66,
    name: "التحريم",
    transliteration: "At-Tahrim",
    translation: "The Prohibition",
    ayahs: 12,
  },
  {
    number: 67,
    name: "الملك",
    transliteration: "Al-Mulk",
    translation: "The Sovereignty",
    ayahs: 30,
  },
  {
    number: 68,
    name: "القلم",
    transliteration: "Al-Qalam",
    translation: "The Pen",
    ayahs: 52,
  },
  {
    number: 69,
    name: "الحاقة",
    transliteration: "Al-Haqqah",
    translation: "The Reality",
    ayahs: 52,
  },
  {
    number: 70,
    name: "المعارج",
    transliteration: "Al-Ma'arij",
    translation: "The Ascending Stairways",
    ayahs: 44,
  },
  {
    number: 71,
    name: "نوح",
    transliteration: "Nuh",
    translation: "Noah",
    ayahs: 28,
  },
  {
    number: 72,
    name: "الجن",
    transliteration: "Al-Jinn",
    translation: "The Jinn",
    ayahs: 28,
  },
  {
    number: 73,
    name: "المزمل",
    transliteration: "Al-Muzzammil",
    translation: "The Enshrouded One",
    ayahs: 20,
  },
  {
    number: 74,
    name: "المدثر",
    transliteration: "Al-Muddaththir",
    translation: "The Cloaked One",
    ayahs: 56,
  },
  {
    number: 75,
    name: "القيامة",
    transliteration: "Al-Qiyamah",
    translation: "The Resurrection",
    ayahs: 40,
  },
  {
    number: 76,
    name: "الانسان",
    transliteration: "Al-Insan",
    translation: "The Man",
    ayahs: 31,
  },
  {
    number: 77,
    name: "المرسلات",
    transliteration: "Al-Mursalat",
    translation: "The Emissaries",
    ayahs: 50,
  },
  {
    number: 78,
    name: "النبأ",
    transliteration: "An-Naba",
    translation: "The Tidings",
    ayahs: 40,
  },
  {
    number: 79,
    name: "النازعات",
    transliteration: "An-Nazi'at",
    translation: "Those who drag forth",
    ayahs: 46,
  },
  {
    number: 80,
    name: "عبس",
    transliteration: "Abasa",
    translation: "He Frowned",
    ayahs: 42,
  },
  {
    number: 81,
    name: "التكوير",
    transliteration: "At-Takwir",
    translation: "The Overthrowing",
    ayahs: 29,
  },
  {
    number: 82,
    name: "الإنفطار",
    transliteration: "Al-Infitar",
    translation: "The Cleaving",
    ayahs: 19,
  },
  {
    number: 83,
    name: "المطففين",
    transliteration: "Al-Mutaffifin",
    translation: "The Defrauding",
    ayahs: 36,
  },
  {
    number: 84,
    name: "الإنشقاق",
    transliteration: "Al-Inshiqaq",
    translation: "The Sundering",
    ayahs: 25,
  },
  {
    number: 85,
    name: "البروج",
    transliteration: "Al-Buruj",
    translation: "The Mansions of the Stars",
    ayahs: 22,
  },
  {
    number: 86,
    name: "الطارق",
    transliteration: "At-Tariq",
    translation: "The Nightcommer",
    ayahs: 17,
  },
  {
    number: 87,
    name: "الأعلى",
    transliteration: "Al-A'la",
    translation: "The Most High",
    ayahs: 19,
  },
  {
    number: 88,
    name: "الغاشية",
    transliteration: "Al-Ghashiyah",
    translation: "The Overwhelming",
    ayahs: 26,
  },
  {
    number: 89,
    name: "الفجر",
    transliteration: "Al-Fajr",
    translation: "The Dawn",
    ayahs: 30,
  },
  {
    number: 90,
    name: "البلد",
    transliteration: "Al-Balad",
    translation: "The City",
    ayahs: 20,
  },
  {
    number: 91,
    name: "الشمس",
    transliteration: "Ash-Shams",
    translation: "The Sun",
    ayahs: 15,
  },
  {
    number: 92,
    name: "الليل",
    transliteration: "Al-Layl",
    translation: "The Night",
    ayahs: 21,
  },
  {
    number: 93,
    name: "الضحى",
    transliteration: "Ad-Duhaa",
    translation: "The Morning Hours",
    ayahs: 11,
  },
  {
    number: 94,
    name: "الشرح",
    transliteration: "Ash-Sharh",
    translation: "The Relief",
    ayahs: 8,
  },
  {
    number: 95,
    name: "التين",
    transliteration: "At-Tin",
    translation: "The Fig",
    ayahs: 8,
  },
  {
    number: 96,
    name: "العلق",
    transliteration: "Al-Alaq",
    translation: "The Clot",
    ayahs: 19,
  },
  {
    number: 97,
    name: "القدر",
    transliteration: "Al-Qadr",
    translation: "The Power",
    ayahs: 5,
  },
  {
    number: 98,
    name: "البينة",
    transliteration: "Al-Bayyinah",
    translation: "The Clear Proof",
    ayahs: 8,
  },
  {
    number: 99,
    name: "الزلزلة",
    transliteration: "Az-Zalzalah",
    translation: "The Earthquake",
    ayahs: 8,
  },
  {
    number: 100,
    name: "العاديات",
    transliteration: "Al-Adiyat",
    translation: "The Courser",
    ayahs: 11,
  },
  {
    number: 101,
    name: "القارعة",
    transliteration: "Al-Qari'ah",
    translation: "The Calamity",
    ayahs: 11,
  },
  {
    number: 102,
    name: "التكاثر",
    transliteration: "At-Takathur",
    translation: "The Rivalry in world increase",
    ayahs: 8,
  },
  {
    number: 103,
    name: "العصر",
    transliteration: "Al-Asr",
    translation: "The Declining Day",
    ayahs: 3,
  },
  {
    number: 104,
    name: "الهمزة",
    transliteration: "Al-Humazah",
    translation: "The Traducer",
    ayahs: 9,
  },
  {
    number: 105,
    name: "الفيل",
    transliteration: "Al-Fil",
    translation: "The Elephant",
    ayahs: 5,
  },
  {
    number: 106,
    name: "قريش",
    transliteration: "Quraysh",
    translation: "Quraysh",
    ayahs: 4,
  },
  {
    number: 107,
    name: "الماعون",
    transliteration: "Al-Ma'un",
    translation: "The Small kindnesses",
    ayahs: 7,
  },
  {
    number: 108,
    name: "الكوثر",
    transliteration: "Al-Kawthar",
    translation: "The Abundance",
    ayahs: 3,
  },
  {
    number: 109,
    name: "الكافرون",
    transliteration: "Al-Kafirun",
    translation: "The Disbelievers",
    ayahs: 6,
  },
  {
    number: 110,
    name: "النصر",
    transliteration: "An-Nasr",
    translation: "The Divine Support",
    ayahs: 3,
  },
  {
    number: 111,
    name: "المسد",
    transliteration: "Al-Masad",
    translation: "The Palm Fiber",
    ayahs: 5,
  },
  {
    number: 112,
    name: "الإخلاص",
    transliteration: "Al-Ikhlas",
    translation: "The Sincerity",
    ayahs: 4,
  },
  {
    number: 113,
    name: "الفلق",
    transliteration: "Al-Falaq",
    translation: "The Daybreak",
    ayahs: 5,
  },
  {
    number: 114,
    name: "الناس",
    transliteration: "An-Nas",
    translation: "Mankind",
    ayahs: 6,
  },
];
